### PR TITLE
Make the package installable

### PR DESCRIPTION
**Pull request by Tim-Jackins**
You'll need to change the name of the repository for this pull to work properly. I hope you're ok with pull requests.

### CODE REVIEW

**Comment by davidhaller** [comment]
Nice work Tim, great job!

About the name change: In your setup.py, it still has the old URL, so we would need to change that, too. Or we just keep the old URL; is there any name conflict I'm not aware of?

**Comment by Tim-Jackins** [comment]
Yes you would need to change the name. I called my fork dnd-roller but you can call it whatever. If you change the name of the repo let me know and I can add a commit to fix the url.

**Comment by Tim-Jackins** [comment]
Hey, the package won't be able to be installed! We'll need to either change the name of the package or the name of the repo.

**Comment by Tim-Jackins** [comment]
Hmm, I had some weird behavior when installing from my fork but it looks like it's working properly!

**Pull request merged**
